openwebf/webf

webf/lib/src/rendering/sliver_list.dart

fix RenderSliverListLayout not support overflowLayout

fix(overflowlayout): fix RenderSliverListLayout's overflowLayout null

---

webf/lib/src/gesture/gesture_dispatcher.dart

Event should be filtered by developer themselves, the frequency limit may lead to laggins

refactor: remove event dispatch throttle

---

webf/example/assets/bundle.js
webf/lib/src/css/style_declaration.dart
webf/lib/src/devtools/modules/css.dart

Revert "Fix/devtolls css property"

---

performance_tests/test/widget_test.dart

The constructor "MyApp" isn't a const constructor.

fix: syntax error

---

bridge/bindings/qjs/script_value.cc
integration_tests/lib/main.dart
integration_tests/specs/modules/method-channel.ts

Fix method channel return int64

---

bridge/third_party/quickjs/src/core/bytecode.c

https://github.com/openwebf/webf/issues/128

fix: read column table crash for kbc1 file on M1

---

bridge/core/css/legacy/css_style_declaration.cc
bridge/core/css/legacy/css_style_declaration_test.cc

Reverts openwebf/webf#155
The test failed.

Revert "fix: remove the property filter."

---

webf/lib/src/html/input.dart

Fix
```
flutter: LateInitializationError: Field '_focusNode@1426021449' has not been initialized.
#0      BaseInputElement._focusNode (package:webf/src/html/input.dart)
#1      BaseInputElement.dispose (package:webf/src/html/input.dart:352:5)
#2      WebFViewController.disposeEventTarget (package:webf/src/launcher/controller.dart:666:12)
#3      flushUICommand (package:webf/src/bridge/to_native.dart:458:16)
#4      flushUICommandWithContextId (package:webf/src/bridge/to_native.dart:406:5)
#5      _flushUICommand (package:webf/src/bridge/from_native.dart:342:3)
#6      _FfiCallback_flushUICommand (dart:ffi)
#7      FfiTrampoline (dart:ffi)
#8      _setTimeout.<anonymous closure>._runCallback (package:webf/src/bridge/from_native.dart:199:13)
#9      _setTimeout.<anonymous closure> …
```

fix: fix input focusnode error.

---

bridge/polyfill/src/location.ts
integration_tests/specs/navigator/history.ts
webf/CHANGELOG.md
webf/lib/src/module/history.dart
webf/pubspec.yaml

1. Fix `history.back()` cause page reload.
2. Fix `location.href` never changed.
3. Add history test specs.

Fix: History API

---

webf/lib/src/dom/document.dart
webf/lib/src/dom/element.dart
webf/lib/src/rendering/box_model.dart

scheduleFrame to make sure all inactive renderObject are finalized.

fix: fix renderObject didn't disposed when frame update paused.

---

bridge/polyfill/package.json
bridge/polyfill/src/fetch.ts
integration_tests/specs/css/css-animations/animation-delay-001-manual.html
webf/lib/src/css/computed_style_declaration.dart
webf/lib/src/css/keywords.dart
webf/lib/src/css/style_property.dart
webf/lib/src/css/values/length.dart
webf/lib/src/devtools/modules/css.dart

https://github.com/openwebf/webf/issues/233

fix: Query computed style for kebabize property name

---

webf/lib/src/gesture/monodrag.dart

Fix running on the desktop can not scroll with trackpad.

fix: fix pan scroll on desktop versions.

---

bridge/core/dom/node.d.ts
bridge/core/dom/node.h
integration_tests/specs/dom/nodes/node.ts

Add the following DOM API support to rendering with Vue createSSRApp API.
1. Add Node.hasChildNodes API support.

feat: add Vue SSR support.

---

bridge/CMakeLists.txt
bridge/third_party/quickjs/src/core/builtins/js-promise.c
bridge/third_party/quickjs/src/core/runtime.c
bridge/third_party/quickjs/src/core/types.h
bridge/third_party/quickjs/tests/test_promise_gc_crash.js

1. fix issue: https://github.com/openwebf/webf/issues/265
2. add lto to quickjs

fix: pending promise crash for early gc and add lto to quickjs

---

bridge/CMakeLists.txt
bridge/bindings/qjs/script_wrappable.cc
bridge/bindings/qjs/script_wrappable.h
bridge/core/dom/events/event_target.h
bridge/core/executing_context.cc
bridge/core/executing_context.h
bridge/core/frame/window_or_worker_global_scope.cc
bridge/core/frame/window_or_worker_global_scope.d.ts
bridge/core/frame/window_or_worker_global_scope.h
bridge/core/html/html_image_element.cc
bridge/core/html/html_image_element.d.ts
bridge/core/html/html_image_element.h
integration_tests/specs/dom/elements/img.ts
webf/lib/src/dom/element.dart

Fix `<img />` can not be GC even if it's detached or removed from the DOM tree.

fix: fix HTMLImageElement leak.

---

bridge/third_party/quickjs/src/core/bytecode.c

fix: ic free atom crash when ctx early free

---

bridge/core/dom/document.cc
bridge/core/dom/document.d.ts
bridge/core/dom/document.h
integration_tests/specs/dom/nodes/document.ts

https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView

feat: add document.defaultView API.

---

bridge/test/webf_test_context.cc
bridge/test/webf_test_env.cc

Resolves https://github.com/openwebf/webf/issues/362 if approved.

Description of this test assertion implies that we should use not equals

---

bridge/core/html/html_script_element.d.ts
bridge/test/webf_test_env.cc
webf/lib/src/html/script.dart

feat:support script add readystate

feat:support script add readystate

---

README.md
bridge/polyfill/src/index.ts
bridge/polyfill/src/websocket.ts
webf/example/assets/bundle.js
webf/example/lib/main.dart
webf/example/pubspec.yaml
webf/lib/src/css/transition.dart
webf/lib/src/module/module_manager.dart
webf/lib/src/module/websocket.dart
webf/pubspec.yaml

1. Add websocket to webf as buint-in module

feat: add websocket module

---

bridge/core/css/computed_css_style_declaration.cc
bridge/core/css/computed_css_style_declaration.h
bridge/core/css/css_style_declaration.d.ts
bridge/core/css/css_style_declaration.h
bridge/core/css/inline_css_style_declaration.cc
bridge/core/css/inline_css_style_declaration.h
bridge/core/html/parser/html_parser.cc
bridge/core/html/parser/html_parser.h
bridge/foundation/ui_command_buffer.h
integration_tests/specs/css/css-variables/variable-cssText.html
integration_tests/specs/cssom/cssom-cssText-serialize.html
webf/lib/src/bridge/to_native.dart
webf/lib/src/css/style_declaration.dart
webf/lib/src/css/style_property.dart
webf/lib/src/dom/element.dart
webf/lib/src/launcher/controller.dart

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssText

Feat: add CSSStyleDeclaration.cssText support

---

scripts/tasks.js

https://developer.android.com/studio/command-line/variables

Use `ANDROID_HOME` as suggested instead of `ANDROID_SDK_HOME`

---

webf/lib/src/module/async_storage.dart
webf/lib/src/module/clipboard.dart
webf/lib/src/module/fetch.dart
webf/lib/src/module/method_channel.dart
webf/lib/src/module/websocket.dart

Revert "refactor: use async await instead of .then for better readability."

---

bridge/core/css/inline_css_style_declaration.cc
integration_tests/specs/cssom/cssom-setCssText-serialize.html

Fix set inline-styles via CSSStyleDeclaration.style.cssText API.

fix: fix set Element.style.cssText API.

---

bridge/core/binding_call_methods.json5
bridge/core/dom/document.d.ts
webf/lib/src/dom/document.dart
webf/lib/src/launcher/controller.dart

(downstream https://github.com/AstroxNetwork/flutter_webf/commit/ffe9cc6f501036e402bbbf7344c0858e0116cb33)
Corresponds to title changes in the document.

✨ `WebFController.onTitleChanged`

---

.github/workflows/example_build.yml
.github/workflows/integration_test_flutter.yml
webf/analysis_options.yaml
webf/lib/src/css/position.dart
webf/lib/src/css/positioned.dart
webf/lib/src/css/values/length.dart
webf/lib/src/dom/element.dart
webf/lib/src/dom/sliver_manager.dart
webf/lib/src/launcher/controller.dart
webf/lib/src/rendering/box_model.dart
webf/lib/src/rendering/event.dart
webf/lib/src/rendering/intersection_observer.dart
webf/lib/src/rendering/paragraph.dart
webf/pubspec.yaml

Add flutter 3.13.5 support.
This the the prerelease version of WebF 0.16.0.

feat: add flutter 3.13.5 support.

---

integration_tests/lib/webf_tester.dart
integration_tests/specs/window/location.ts
webf/lib/src/module/location.dart

Correct the results returned by the Location API.
This PR also fixes the unexpected behavior of React-router and vue-router, both of which depend on the Location API.

fix: fix location search and hostname params.

---

webf/lib/src/bridge/binding.dart

fix: fix event.target still can be pointed by event after finalized by JavaScript GC.

---

webf/lib/src/rendering/box_decoration_painter.dart

fix div update backgroundimage do not update .

fix: bg_image_update not update error

---

bridge/core/binding_call_methods.json5
bridge/core/dom/element.cc
bridge/core/dom/element.d.ts
bridge/core/dom/element.h
integration_tests/specs/dom/elements/custom-element.ts
webf/lib/src/dom/element.dart

feat: add Element.getCliengRects support

---

webf/lib/src/rendering/flex.dart

fix: min precision case some error and waste cpu

---

bridge/core/binding_object.h
bridge/core/dart_context_data.h
bridge/core/dart_isolate_context.cc
bridge/core/dart_isolate_context.h
bridge/core/dom/mutation_observer.cc
bridge/core/dom/mutation_observer.h
bridge/core/dom/mutation_observer_registration.cc
bridge/core/dom/mutation_observer_registration.h
bridge/core/dom/node.cc
bridge/core/dom/node.h
bridge/core/dom/node_data.h
bridge/core/dom/space_split_string.cc
bridge/core/executing_context.h

replace `<set>` to `<unordered_set>` to get better performance results.

feat: optimize MutationObserver performance.

---

scripts/build_ios_framework.js
webf/lib/src/html/html.dart

https://github.com/openwebf/webf/assets/4409743/1b656927-f084-4e3c-8e02-57acd819d11f

fix: fix textarea elements in ios/android can not auto unfocus.

---

bridge/core/dart_methods.cc

申请了内存，但是没有给内存里面填写内容，导致console.log在前台打印不出来。

fix js log does not show in terrminal and devtools

---

webf/lib/src/dom/element.dart
webf/lib/src/launcher/controller.dart
webf/lib/src/rendering/box_model.dart
webf/lib/src/widget/webf.dart

Fixed https://github.com/openwebf/webf/issues/573

fix: fix input when resume apps.

---

bridge/bindings/qjs/converter_impl.h
bridge/bindings/qjs/qjs_function.cc
bridge/bindings/qjs/qjs_function.h
bridge/core/dom/events/event_target.cc
integration_tests/specs/dom/nodes/event-target.ts

Fixed https://github.com/openwebf/webf/issues/531

feat: add support for object event listener.

---

bridge/CMakeLists.txt
bridge/core/api/comment.cc
bridge/core/api/document.cc
bridge/core/api/document_fragment.cc
bridge/include/plugin_api/comment.h
bridge/include/plugin_api/document.h
bridge/include/plugin_api/document_fragment.h
bridge/rusty_webf_sys/src/comment.rs
bridge/rusty_webf_sys/src/document.rs
bridge/rusty_webf_sys/src/document_fragment.rs
bridge/rusty_webf_sys/src/lib.rs

- complement createElement methods
- add createDocumentFragment
- add createComment

Feat/rust support: add new method bindings

---

.github/workflows/integration_test_flutter.yml
bridge/scripts/code_generator/package.json
integration_tests/lib/bridge/to_native.dart
integration_tests/macos/Runner.xcodeproj/project.pbxproj
integration_tests/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
integration_tests/spec_group.json
integration_tests/specs/css/css-display/opacity.ts
webf/example/macos/Runner.xcodeproj/project.pbxproj
webf/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
webf/lib/src/bridge/binding.dart
webf/lib/src/bridge/from_native.dart
webf/lib/src/bridge/to_native.dart
webf/lib/src/dom/sliver_manager.dart
webf/lib/src/launcher/controller.dart

This patch adds support for Flutter 3.22.x without breaking compatibility with versions 3.13.x, 3.16.x, and 3.19.x.

Feat: Add flutter 3.22 support

---

webf/example/macos/Runner/AppDelegate.swift
webf/lib/src/launcher/controller.dart

Add Flutter 3.24.x version support.
Fixed https://github.com/openwebf/webf/issues/643

feat: add flutter 324 support.

---

bridge/CMakeLists.txt
bridge/core/api/event.cc
bridge/core/api/event_target.cc
bridge/include/plugin_api/event.h
bridge/include/plugin_api/event_target.h
bridge/rusty_webf_sys/src/character_data.rs
bridge/rusty_webf_sys/src/comment.rs
bridge/rusty_webf_sys/src/container_node.rs
bridge/rusty_webf_sys/src/document.rs
bridge/rusty_webf_sys/src/document_fragment.rs
bridge/rusty_webf_sys/src/element.rs
bridge/rusty_webf_sys/src/event.rs
bridge/rusty_webf_sys/src/event_target.rs
bridge/rusty_webf_sys/src/html_element.rs
bridge/rusty_webf_sys/src/node.rs
bridge/rusty_webf_sys/src/text.rs
webf/example/rust/src/lib.rs

- add event properties
- add dispatch_event

event & event_target

---

bridge/core/api/document.cc
bridge/core/api/event.cc
bridge/core/api/event_target.cc
bridge/core/api/executing_context.cc
bridge/include/plugin_api/event.h
bridge/include/plugin_api/event_target.h
bridge/rusty_webf_sys/src/event.rs
bridge/rusty_webf_sys/src/event_target.rs
webf/example/rust/src/lib.rs

- add event drop
- fix handler argument from event target to event
- gc count fix

update event handling in Rust API

---

.github/workflows/example_build.yml
webf/example/rust_builder/pubspec.yaml
webf/pubspec.yaml

Fixed https://github.com/openwebf/webf/issues/385
Upgrade intl deps to 0.19.0 and flutter 3.27.1 works.

feat: upgrade intl deps to 0.19.0.
