openwebf/webf

- bridge/core/html/parser/html_parser.cc
Support query dom element in the inline script at the bottom of the body.
```html
<!DOCTYPE html>
<html>
<body>
<div id="button"> Button</div>
<div class="container"></div>
<script>
let button = document.getElementById('button');
</script>
</body>
</html>
```
> fix: should flush ui command before evaluate script when parse html.

- bridge/CMakeLists.txt
Always to run `npm install` for codegen project whether `node_modules` folder exists or not.
> fix: should alway run npm install for codegen project

- webf/android/src/main/java/com/openwebf/webf/WebFPlugin.java
Related from https://github.com/flutter/flutter/issues/73318?from_wecom=1#issuecomment-754598119
> fix: fix android dynamic libraray not found on some devices

- integration_tests/linux/CMakeLists.txt
fix integration tests path problem on linux
> fix: integration tests path problem on linux

- webf/ios/Frameworks/quickjs.xcframework
- webf/ios/Frameworks/webf_bridge.xcframework
- webf/ios/prepare.sh
- webf/ios/quickjs.xcframework
- webf/ios/webf.podspec
- webf/ios/webf_bridge.xcframework
Fix webf_bridge.xcframework and quickjs.xcframework missing when running `flutter build ios-framwork` command.
> Fix: ios build

- .github/workflows/example_build.yml
- .github/workflows/integration_test_flutter.yml
- bridge/bindings/qjs/atomic_string.cc
- bridge/bindings/qjs/atomic_string.h
- bridge/bindings/qjs/converter_impl.h
- bridge/bindings/qjs/idl_type.h
- bridge/core/built_in_string.json5
- bridge/core/css/legacy/css_style_declaration.d.ts
- bridge/core/dom/character_data.cc
- bridge/core/dom/character_data.h
- bridge/core/dom/container_node.cc
- bridge/core/dom/container_node.h
- bridge/core/dom/document.cc
- bridge/core/dom/document.h
- bridge/core/dom/document_fragment.cc
- bridge/core/dom/document_fragment.h
- bridge/core/dom/element.cc
- bridge/core/dom/element.h
- bridge/core/dom/node.cc
- bridge/core/dom/node.h
- bridge/scripts/code_generator/global.d.ts
- bridge/scripts/code_generator/src/idl/analyzer.ts
- bridge/scripts/code_generator/src/idl/declaration.ts
- bridge/scripts/code_generator/src/idl/generateSource.ts
- integration_tests/specs/dom/nodes/nodeValue.ts
- integration_tests/specs/dom/nodes/textContent.ts
WebF doesn't support `DOMString?` DOM IDL type before. All `null` value is changed to
`''` empty string. This isn't right. This commit is to support it.
- AtomicString of empty string has two types now, '' and null.
- Add `IsNull()` instance method to check a string is null.
- Add `Null()` static method to get null string like `Empty()`.
- Add `LegacyNullToEmptyString` typescript type to implement `[LegacyNullToEmtpyString]` attribute for DOMString.
- Add test for textContent/nodeValue.
- Add `built_in_string::kNULL`.
- Support `\0` in AtomicString for set and get.
- Install chrpath for ci
> feat: AtomicString support null like empty string

- webf/lib/src/gesture/scrollable.dart
- webf/lib/src/widget/widget_element.dart
The touch slop is different between iOS and Android devices. Should read it from window instead of using defaults.
> fix: sync gesture settings from window.

- integration_tests/specs/navigator/history.ts
- webf/lib/src/module/history.dart
support optional URL params for History.pushState API.
> fix: fix history pushState()

- integration_tests/specs/dom/elements/custom-element.ts
- webf/lib/src/html/img.dart
- webf/lib/src/widget/element_flutter_element_adapter.dart
For WebFHTMLElementToFlutterElementAdaptor, should unmount all the children before unmounting itself.
> fix: fix widget element unmount renderObject.

- bridge/CMakeLists.txt
- bridge/bindings/qjs/script_wrappable.cc
- bridge/third_party/quickjs/include/quickjs/quickjs-opcode.h
- bridge/third_party/quickjs/include/quickjs/quickjs.h
- bridge/third_party/quickjs/src/core/builtins/js-operator.c
- bridge/third_party/quickjs/src/core/builtins/js-proxy.c
- bridge/third_party/quickjs/src/core/builtins/js-reflect.c
- bridge/third_party/quickjs/src/core/bytecode.c
- bridge/third_party/quickjs/src/core/function.c
- bridge/third_party/quickjs/src/core/gc.c
- bridge/third_party/quickjs/src/core/ic.c
- bridge/third_party/quickjs/src/core/ic.h
- bridge/third_party/quickjs/src/core/object.c
- bridge/third_party/quickjs/src/core/object.h
- bridge/third_party/quickjs/src/core/parser.c
- bridge/third_party/quickjs/src/core/parser.h
- bridge/third_party/quickjs/src/core/runtime.c
- bridge/third_party/quickjs/src/core/types.h
**What kind of change does this PR introduce?**
Add self poly inline cache to quickjs
**Does this PR introduce a breaking change?**
No.
**Why submit this PR?**
- improve the performance of object get / set operations;
**Does the test262 pass?**
Yes.
**Benchmark**
> - GCC 8.3.0
> - AMD Ryzen5 3600
> - Linux 5.15.77-amd64-desktop
```shell
> hyperfine --warmup 1 --runs 3 --show-output "./bin/qjs ./bin/index.js"
```
|               | master    | feat/ic |      |
| ------------- | ---------- | ---------- | ------ |
| Richards      | 752        | 888      |  +18.0%  |
| Crypto      | 618        | 713      |  +15.3%  |
| RayTrace      | 807        | 833       | +3.2%   |
| NavierStokes      | 1497        | 1319      | -11.8%  |
| DeltaBlue      | 744        | 845       |  +13.5% |
| Score …
>  feat: add Self Poly Inline Cache for quickjs

- bridge/CMakeLists.txt
- bridge/core/dom/document.cc
- bridge/core/dom/document.d.ts
- bridge/core/dom/document.h
- bridge/core/dom/element.cc
- bridge/core/dom/element.d.ts
- bridge/core/dom/element.h
- bridge/core/dom/element_namespace_uris.json5
- bridge/core/html/custom/widget_element.cc
- bridge/core/html/html_element.cc
- bridge/core/html/html_element.h
- bridge/core/html/html_unknown_element.cc
- bridge/core/html/html_unknown_element.h
- bridge/foundation/ui_command_buffer.h
- integration_tests/specs/dom/nodes/createElementNS.ts
- webf/lib/src/bridge/to_native.dart
- webf/lib/src/dom/document.dart
- webf/lib/src/dom/element.dart
- webf/lib/src/dom/element_registry.dart
- webf/lib/src/launcher/controller.dart
RFC: SVG
This PR is the dep of the SVG supports.
Changes:
> feat: add namespace support

- .github/workflows/code_linter.yml
- .github/workflows/contributors.yml
- .github/workflows/example_build.yml
- .github/workflows/integration_test_flutter.yml
- .github/workflows/publish_to_dart_dev.yml
- .github/workflows/publish_to_dart_dev_nightly.yml
- .gitmodules
- bridge/CMakeLists.txt
- bridge/bindings/qjs/atomic_string.cc
- bridge/scripts/code_generator/templates/idl_templates/interface.cc.tpl
- bridge/third_party/quickjs/include/quickjs/cutils.h
- bridge/third_party/quickjs/src/core/base.h
- bridge/third_party/quickjs/src/core/malloc.c
- bridge/third_party/quickjs/src/core/malloc.h
- bridge/third_party/quickjs/src/core/runtime.c
- bridge/third_party/quickjs/src/cutils.c
- bridge/third_party/quickjs/src/libbf.c
- bridge/third_party/quickjs/src/libregexp.c
- bridge/third_party/quickjs/src/libunicode.c
**Benchmark**
> - GCC 11.3.0
> - Intel x2676v3 3.0Ghz
> - Linux 5.15.0-58-generic
|               | master    | feat/mimalloc |      |
| ------------- | ---------- | ---------- | ------ |
| Richards      | 511 | 533 |  +4.3%  |
| Crypto      | 572 | 610 |  +6.6%  |
| RayTrace      | 648 | 768 | +18.5%   |
| NavierStokes      | 1034 | 1053 | +3.2%  |
| DeltaBlue      | 578 | 602 |  +4.1% |
| Score (version 7)     | 647 | 692 | +6.9%  |
> feat: replace malloc to mimalloc

- webf/lib/src/foundation/http_client.dart
- webf/lib/src/foundation/http_client_response.dart
- webf/lib/src/module/fetch.dart
We should share the HttpClient instance between multiple WebF pages and keep the existing connection alive to avoid establishing a new TCP connection with the same URL every time.
> feat: share HttpClient between multiple WebF pages to keep the exist connection alive.

- webf/lib/src/css/element_rule_collector.dart
- webf/lib/src/dom/document.dart
- webf/lib/src/launcher/controller.dart
```
The DOMContentLoaded event fires when the HTML document has been completely parsed, and all deferred scripts (<script defer src="…"> and <script type="module">) have downloaded and executed. It doesn't wait for other things like images, subframes, and async scripts to finish loading.
```
> fix: fix dom content loaded event trigger condition.

- webf/lib/src/bridge/to_native.dart
- webf/lib/src/foundation/bundle.dart
- webf/lib/src/html/script.dart
- webf/lib/src/painting/cached_network_image.dart
When loading web pages, the page will downloads scripts and stylesheets. We have two different types of caches to optimize page load times. One is the HttpCache, which caches the HTTP response results and may replace the actual http requests if they are valid to use. The second one is the bytecode cache, which caches the quickjs bytecode results from raw javascript source codes to reduce the parsing time of the quickjs engine. 
All these cache files are stored on client's disk. If these cache files become corrupted, they can break the page, even if the files on the remote server are correct. 
To avoid potential load errors, we have implemented fallback operations that invalidate caches if the quickjs report errors during the initial stage.
Additionnal features:  decompress gzip content to …
> feat: invalidate cache when expect errors

- integration_tests/specs/dom/nodes/element.ts
- webf/lib/src/dom/bounding_client_rect.dart
BindingObjects are shared between C++ and Dart and will be freed by the QuickJS garbage collector in the end. We should return a new instance from Dart to C++ every time.
> fix: binding object should be returned with new instance.

- bridge/core/dom/document.h
- bridge/core/dom/frame_request_callback_collection.cc
- bridge/core/dom/frame_request_callback_collection.h
- bridge/core/dom/scripted_animation_controller.cc
- bridge/core/dom/scripted_animation_controller.h
- bridge/core/frame/dom_timer_coordinator.cc
- integration_tests/specs/window/global.ts
- webf/lib/src/launcher/controller.dart
Fix app crashed when canceling animationFrame inside of frame callback in iOS devices.
Crash demo:
```javascript
const div = document.createElement('div');
div.onclick = () => {
let t = requestAnimationFrame(() => {
cancelAnimationFrame(t);
document.body.appendChild(document.createTextNode('cleared'));
});
};
div.textContent = 'click';
document.body.appendChild(div);
```
> fix: fix crash when cancelAnimationFrame in frame callbacks.

- bridge/core/frame/dom_timer_coordinator.cc
- bridge/core/frame/window_or_worker_global_scope.cc
- integration_tests/spec_group.json
- integration_tests/specs/dom/elements/img.ts
- webf/lib/src/html/img.dart
- webf/lib/src/rendering/flow.dart
- webf/lib/src/rendering/overflow.dart
Prevent GIF images' individual frames from causing a relayout of the entire render object tree.
> fix: fix GIF images cause rendering optimze rendering performance overhead.

- webf/lib/src/launcher/controller.dart
- webf/lib/src/widget/webf.dart
Add a Dart API callback when the DOMContentLoaded event is triggered.
```dart
WebF(
onDOMContentLoaded: (controller) {
print('dom content loaded ${ controller.view.document.isConnected}');
},
),
```
> feat: add DOMContentLoaded API.

- bridge/scripts/code_generator/src/idl/generateSource.ts
- integration_tests/specs/window/global.ts
The code_generator does not generate the correct code for accessing 'this' in JavaScript functions when the parameter count is greater than 1.
> fix: fix crashed when access global functions with multiple parameters.

- bridge/core/dart_methods.cc
- integration_tests/specs/css/css-flexbox/flex_shrink.ts
- integration_tests/specs/dom/elements/img.ts
- integration_tests/specs/dom/elements/script.ts
- webf/lib/src/bridge/binding.dart
- webf/lib/src/html/img.dart
- webf/lib/src/rendering/box_model.dart
- webf/lib/src/rendering/intersection_observer.dart
- webf/lib/src/rendering/webf_render_list.dart
Significantly optimize the image loading strategy and fix potential memory leaks.
1. [x] Collaborate with Flutter's ImageCache. Each HTMLImageElement will have a reference to an ImageProvider. If another HTMLElement uses the same URL, it will obtain the same ImageProvider from the ImageCache, preventing repeated requests and decoding.
2. [x] If an HTMLImageElement has a fixed size (both width and height are defined), a new ImageProvider with a fixed size will replace the previous unsized ImageProvider. When an ImageProvider has a fixed size, it resizes the image to a suitable size to reduce memory usage if the image is larger than its actual display size.
3. [x] If an HTMLImageElement's renderObject is detached from the RenderObject tree, an ImageStreamCompleterHandle will be created to …
> Feat: optimize image load

- webf/lib/src/foundation/bytecode_cache.dart
- webf/pubspec.yaml
In some rare cases, the cached bytecode may be corrupt. To ensure the cached bytecode is correct, add a checksum using the CRC32 algorithm.
> feat: validate bytecode cache with CRC32 checksum.

- bridge/core/frame/dom_timer.cc
- bridge/core/frame/dom_timer.h
- bridge/core/frame/dom_timer_coordinator.cc
- bridge/core/frame/dom_timer_coordinator.h
- bridge/core/frame/window_or_worker_global_scope.cc
- webf/example/ios/Podfile
- webf/example/ios/Runner.xcodeproj/project.pbxproj
- webf/example/ios/Runner/Info.plist
In some rare cases, DOMTimer may be accessed even if the timer has been canceled and removed from the DOMCoordinator. This could cause a BAD ACCESS crash since the timer's memory has been freed.
In this patch, we terminate the timer but do not immediately free it.
> fix: protect DOMTimers until the ExecutingContext exits.

- bridge/core/binding_call_methods.json5
- bridge/core/dom/document.cc
- bridge/core/dom/document.d.ts
- bridge/core/dom/document.h
- bridge/core/dom/events/event_target.h
- integration_tests/specs/dom/nodes/document.ts
- webf/lib/src/dom/binding.dart
- webf/lib/src/dom/document.dart
- webf/lib/src/launcher/controller.dart
feat:document add visibilitychange and support api visibilityState, hidden
> feat:support api visibilityState, hidden

- bridge/bindings/qjs/js_event_listener.h
- bridge/bindings/qjs/qjs_function.h
Using .get() allows us to compare the raw value of memory address underlying each, which would then make the comparison valid
Fixes https://github.com/openwebf/webf/issues/351
> Comparison without operator overload failure

- bridge/core/html/html_template_element.cc
- bridge/core/html/html_template_element.h
- integration_tests/specs/dom/elements/template.ts
Fix the DocumentFragment instance leaks when GC template elements.
> fix: fix template element's content property cause mem leaks.

- bridge/CMakeLists.txt
- bridge/bindings/qjs/converter_impl.h
- bridge/core/dom/character_data.d.ts
- bridge/core/dom/child_node.d.ts
- bridge/core/dom/comment.h
- bridge/core/dom/document.d.ts
- bridge/core/dom/document_fragment.d.ts
- bridge/core/dom/element.cc
- bridge/core/dom/element.d.ts
- bridge/core/dom/node.cc
- bridge/core/dom/node.h
- bridge/core/dom/parent_node.cc
- bridge/core/dom/parent_node.d.ts
- bridge/core/dom/parent_node.h
- bridge/core/html/canvas/canvas_rendering_context_2d.cc
- bridge/polyfill/src/dom.ts
- bridge/scripts/code_generator/src/idl/analyzer.ts
- bridge/scripts/code_generator/src/idl/generateHeader.ts
- bridge/scripts/code_generator/src/idl/generateSource.ts
- bridge/scripts/code_generator/src/idl/generateUnionTypes.ts
- bridge/scripts/code_generator/templates/idl_templates/union.cc.tpl
- bridge/scripts/code_generator/templates/idl_templates/union.h.tpl
- integration_tests/runtime/global.ts
- integration_tests/specs/dom/nodes/child-node.ts
- integration_tests/specs/dom/nodes/parent-node.ts
- scripts/generate_binding_code.js
- webf/lib/src/foundation/cookie_jar/file_storage.dart
1. Add `append()` and `prepend()` support for [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element/append), [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document/append) and [DocumentElement](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment/append).
2. Add `before()` and `after()` support for [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element/before) and [CharaterData](https://developer.mozilla.org/en-US/docs/Web/API/CharacterData/before).
> Feat: add `append()`, `prepend()`, `before()` and `after()` support.

- bridge/core/frame/window_or_worker_global_scope.cc
In some rare user cases, `handleTransientCallback` and `handlePersistentCallback` could be fired when the ExecutionContext has already been freed.
> fix: check ExecutingContext is alive at timer callbacks.

- bridge/webf_bridge_test.cc
When the integration crashes, it will print the following error message to help us diagnose the problems.
```
flutter: Local HTTP server started at: http://127.0.0.1:34170
Assertion failed: (p->ref_count > 0), function gc_decref_child, file gc.c, line 684.
Error: signal 6:
0   libwebf_test.dylib                  0x0000000123a4bb30 _Z7handleri + 32
1   libsystem_platform.dylib            0x00000001a4062a84 _sigtramp + 56
2   libsystem_pthread.dylib             0x00000001a4033c28 pthread_kill + 288
3   libsystem_c.dylib                   0x00000001a3f41ae8 abort + 180
4   libsystem_c.dylib                   0x00000001a3f40e44 err + 0
5   libquickjs.dylib                    0x00000001025b3940 gc_decref.cold.1 + 0
6   libquickjs.dylib                    0x00000001025452f0 gc_decref + 0
7 …
```
> feat: dump stacktrace when integration test crashed.

- bridge/CMakeLists.txt
- bridge/test/webf_test_env.cc
- bridge/third_party/quickjs/include/quickjs/cutils.h
- bridge/third_party/quickjs/src/core/base.h
- bridge/third_party/quickjs/src/core/malloc.c
- bridge/third_party/quickjs/src/core/malloc.h
- bridge/third_party/quickjs/src/core/runtime.c
- bridge/third_party/quickjs/src/cutils.c
- bridge/third_party/quickjs/src/libunicode.c
- scripts/tasks.js
Use the system's malloc library instead of the default mimalloc by executing the following commands:
```
USE_SYSTEM_MALLOC=true npm run build:bridge:macos
```
> feat: add options to disable mimalloc.

- bridge/core/script_state.cc
DartWorker cannot access the runtime_ member in ScriptState; it only belongs to the Flutter.ui thread.
In this case, we read the JSRuntime from JSContext instead.
```
Thread 20 Crashed:: DartWorker
0   libquickjs.dylib              	       0x10501db28 init_list_head + 0 (list.h:46) [inlined]
1   libquickjs.dylib              	       0x10501db28 gc_decref + 4 (gc.c:696) [inlined]
2   libquickjs.dylib              	       0x10501db28 JS_RunGC + 28 (gc.c:797)
3   libwebf.dylib                 	       0x10555b750 webf::ScriptState::~ScriptState() + 24 (script_state.cc:31) [inlined]
4   libwebf.dylib                 	       0x10555b750 webf::ScriptState::~ScriptState() + 44 (script_state.cc:26)
5   libwebf.dylib                 	       0x1055598c8 webf::ExecutingContext::~ExecutingContext() + …
```
> fix: fix crashed when shutdown the app.

- webf/lib/src/module/local_storage.dart
Hive only supports accessing a resource from one instance, and it creates a lock file to avoid conflicts.
If two Dart isolates load the same URL of WebF pages, they will point to the same Hive lock file and report the following error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/Users/andycall.dong/Library/Caches/WebF/LocalStorage/_webf_11988048.lock' (OS Error: Resource temporarily unavailable, errno = 35)
#0      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1002:9)
<asynchronous suspension>
#1      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81:5)
<asynchronous suspension>
#2      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
<asynchronous …
```
> fix: fix Resource temporarily unavailable for Hive lock file.

- bridge/core/dart_isolate_context.cc
- bridge/core/dart_isolate_context.h
- bridge/core/dom/document.cc
- bridge/core/script_state.cc
- bridge/webf_bridge_test.cc
Built-in strings should be initialized once for a corresponding JSRuntime.
> fix: fix built-in string initialized multiples and cause leaks.

- bridge/bindings/qjs/script_value.cc
- bridge/foundation/native_value.h
- bridge/polyfill/src/fetch.ts
- bridge/polyfill/src/xhr.ts
- integration_tests/specs/fetch/fetch.ts
- integration_tests/specs/xhr/xhr.ts
- webf/lib/src/bridge/native_value.dart
- webf/lib/src/module/fetch.dart
1. Add support for setting the [responseType](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) property to 'arraybuffer' or 'blob' on XMLHttpRequest object to receive binary data instead of json or string.
2. Add support for [Response.arraybuffer()](https://developer.mozilla.org/en-US/docs/Web/API/Response/arrayBuffer) method and [Response.blob()](https://developer.mozilla.org/en-US/docs/Web/API/Response/blob) method.
> feat: support receive binary data from fetch and XMLHttpRequest.

- bridge/bindings/qjs/cppgc/member.h
- bridge/bindings/qjs/script_wrappable.cc
- bridge/core/executing_context_data.cc
- bridge/core/executing_context_test.cc
- bridge/core/html/custom/widget_element_test.cc
- bridge/core/timing/performance_test.cc
- bridge/polyfill/src/dom-exception.ts
- bridge/polyfill/src/index.ts
- integration_tests/package.json
- integration_tests/specs/dom/nodes/element.ts
- webf/lib/src/bridge/from_native.dart
The `constructor` property on DOM elements should point to the constructor function of DOM elements.
> fix: fix constructor property on DOM elements.

- webf/lib/src/css/font_face.dart
The base64-encoded content of font-face may cause a parse error. This error should be caught if the input is incorrect.
> fix: try to parse base64 encoded font.

- scripts/tasks.js
Previously, when `ANDROID_NDK_HOME` is not configured, the SDK root will be implied to platform default, rather than checking whether `ANDROID_SDK_HOME` is set. The PR fix that.
> fix: Read `ANDROID_SDK_HOME` before implying to platform defaults

- webf/lib/src/css/font_face.dart
In Flutter 3.10, they had add checks for the fonts in loading stage when attach or detach RenderObjects on RenderObject tree.
We needs to delay the font loading to the end of frame to make sure renderObjects are not mutated at that times.
```dart
@override
void attach(PipelineOwner owner) {
super.attach(owner);
// If there's a pending callback that would imply this node was detached
// between the idle phase and the next transientCallbacks phase. The tree
// can not be mutated between those two phases so that should never happen.
assert(!_hasPendingSystemFontsDidChangeCallBack);
PaintingBinding.instance.systemFonts.addListener(_scheduleSystemFontsUpdate);
}
@override
void detach() {
assert(!_hasPendingSystemFontsDidChangeCallBack); …
```
> fix: fix loading fonts cause assertion when remove or attach RenderObjects.

- webf/lib/src/foundation/cookie_jar/file_storage.dart
2023-07-21 11:35:10.176465+0800 Spec[73225:6915320] flutter: Failed to load: Instance of 'Context', reason: PathNotFoundException: Deletion failed, path = '/var/mobile/Containers/Data/Application/C0523E81-7A69-4853-B36D-63ACACEBE1B7/Library/Caches/WebF/cookies/ie0_ps1/.domains' (OS Error: No such file or directory, errno = 2)
2023-07-21 11:35:10.176558+0800 Spec[73225:6915320] flutter: #0      _checkForErrorResponse (dart:io/common.dart:42)
2023-07-21 11:35:10.176592+0800 Spec[73225:6915320] flutter: #1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185)
2023-07-21 11:35:10.176628+0800 Spec[73225:6915320] flutter: #2      _rootRunUnary (dart:async/zone.dart:1406)
2023-07-21 11:35:10.176655+0800 Spec[73225:6915320] flutter: <asynchronous suspension>
2023-07-21 …
> fix:cookie delete file error

- webf/pubspec.yaml
- `intl` is relatively stable but critical for SDK packages to depend on. If we depend on `^0.18.1`, `flutter_localizations` will be failed to resolve from the Flutter SDK.
- Bumping Flutter SDK constraints too to avoid accidently referencing from an older SDK.
> Losen `intl` dependency constraint

- bridge/core/executing_context.cc
- bridge/include/webf_bridge.h
- bridge/webf_bridge.cc
- webf/lib/src/bridge/bridge.dart
- webf/lib/src/bridge/to_native.dart
When multiple Flutter engines are created and the top one pops up, the remaining web page may become unresponsive, leading to the following errors:
> fix: fix event not responding when multiple flutter engine created.

- bridge/bindings/qjs/script_value.cc
- bridge/bindings/qjs/script_value.h
- bridge/core/dom/events/event.cc
- integration_tests/specs/dom/events/event.ts
> fix: fix use-of-free crash of shared string property in event object.

- webf/lib/src/launcher/controller.dart
Fix crash when page reload multiple times with the follow crash stacks:
```
Thread 1 Crashed:: io.flutter.ui
0   libwebf.dylib                 	       0x102ebf3a0 webf::ExecutingContext::dartIsolateContext() const + 0 (executing_context.h:121) [inlined]
1   libwebf.dylib                 	       0x102ebf3a0 webf::UICommandBuffer::addCommand(webf::UICommandItem const&, bool) + 20 (ui_command_buffer.cc:31)
2   libwebf.dylib                 	       0x102ebf380 webf::UICommandBuffer::addCommand(webf::UICommand, std::__1::unique_ptr<webf::SharedNativeString, std::__1::default_delete<webf::SharedNativeString>>&&, void*, void*, bool) + 64 (ui_command_buffer.cc:27)
3   libwebf.dylib                 	       0x102ee5d8c webf::BindingObject::~BindingObject() + 100 (binding_object.cc:42)
4 …
```
> fix: fix crash when reload pages.

- bridge/core/frame/console.cc
- bridge/core/frame/console.d.ts
- bridge/core/frame/console.h
- bridge/polyfill/src/bridge.ts
- bridge/polyfill/src/console.ts
Fix the stack overflow error in Vue.js app when other error throws.
```
InternalError: stack overflow
at <anonymous> (http://localhost:8080/js/chunk-vendors.js:1767:34)
at forEach (native)
at formatTrace (http://localhost:8080/js/chunk-vendors.js:1768:9)
at warn (http://localhost:8080/js/chunk-vendors.js:1732:7)
at <anonymous> (http://localhost:8080/js/chunk-vendors.js:4726:5)
```
> fix: fix JavaScript stack overflow error when print Proxy object.

- webf/lib/src/launcher/controller.dart
- webf/lib/src/widget/webf.dart
(downstream https://github.com/AstroxNetwork/flutter_webf/commit/b3a9a696735165307c021a43aea0ec9b6d37e453)
- Add `resizeToAvoidBottomInsets` to flag for `WebF`, `WebFRootRenderObjectWidget`, and `WebFController`, to determine whether the `WebFViewController` should deal with insets changes.
- Remove the redundant `_prevViewInsets`.
> ✨ Introduce `resizeToAvoidBottomInsets`

- webf/lib/src/module/local_storage.dart
(downstream https://github.com/AstroxNetwork/flutter_webf/commit/eb95a178cad5395a32f6f899c67943e2716e9867)
`Hive.init` will update the `homePath` of the `HiveImpl`, which will lead to newly opened boxes using the new base path.
https://github.com/isar/hive/blob/470473ffc1ba39f6c90f31ababe0ee63b76b69fe/hive/lib/src/hive_impl.dart#L57
This behavior is undesirable and will cause severe storage issues for users.
> 🐛 Avoid `Hive.init` cause conflicts with box paths

- webf/lib/src/gesture/gesture_dispatcher.dart
The target element of a Touch object may be reclaimed by the JavaScript garbage collector, causing it to become invisible and inaccessible.
This update introduces checks to prevent the triggering of events on these invisible DOM targets.
> fix: avoiding trigger touch events to inaccessible dom elements.

- bridge/core/events/touch_event.cc
- bridge/core/input/touch_list.cc
- bridge/core/input/touch_list.h
- integration_tests/specs/dom/events/touchEvent.ts
The following JavaScript code is causing crashes:
```javascript
const container = createElement('div', {}, []);
document.body.appendChild(container);
const touchEvent = new TouchEvent('touchstart');
container.dispatchEvent(touchEvent);
const touchEvent2 = new TouchEvent('touchstart', {});
container.dispatchEvent(touchEvent2);
```
> fix: fix init touchEvent from JS cause crash.

- webf/lib/src/dom/sliver_manager.dart
- webf/lib/src/rendering/box_model.dart
fix sliver child boundingClientRect() return x、y loss offset.
> fix: sliver layout child boundingClientRect offset error

- webf/lib/src/devtools/modules/dom.dart
- webf/lib/src/svg/svg.dart
- webf/lib/src/svg/svg_render_object_builder.dart
- webf/lib/svg.dart
Support select img element in chrome devtool
before:
https://github.com/openwebf/webf/assets/40893153/acfff80b-ba0f-4c08-90be-6d4200b55430
after:
https://github.com/openwebf/webf/assets/40893153/a2540228-da90-4aa0-9732-918770e2cfe4
> fix: devtool select img element

- webf/lib/src/foundation/bundle.dart
- webf/test/src/foundation/bundle.dart
Support override the default content-type for WebFBundle.
```dart
bundle: WebFBundle.fromUrl('assets:assets/bundle.xhtml', contentType: htmlContentType), // This XHTML will treated as HTML file.
```
> feat: support override default contentType for WebFBundle.

- bridge/third_party/quickjs/src/core/object.c
- bridge/third_party/quickjs/src/core/runtime.c
- bridge/third_party/quickjs/src/core/types.h
> - Apple M1 Pro
> - macOS Monterey 12.2.1
> - Clang 13.0.0 arm64-apple-darwin21.3.0
|               | openwebf/quickjs (latest)    | quickjs-ng/quickjs (e995085)       | Improvement (%) |
| ------------- | ---------- | ---------- |-----------|
| Richards      | 1324        | 1250       | +5.92 |
| DeltaBlue        | 1281        | 1139       | +12.46|
| Crypto      | 1314        | 1310       | +0.30|
| RayTrace  | 1648        | 1152       | +43.05  |
| EarleyBoyer     | 2225        | 2151       |  +3.44|
| RegExp     | 296        | 258       | +14.72  |
| Splay     | 2467        | 2169       | +13.73|
| SplayLatency     | 9089        | 8197       | +10.88|
| NavierStokes     | 2576        | 2407       | +7.02|
| PdfJS     | 4208        | 4099       | +2.65 |
| Mandreel     | 1173        | …
> feat: quickjs update add property inline cache

- .github/workflows/integration_test_flutter.yml
- bridge/core/binding_object.cc
- bridge/core/dom/element.cc
- bridge/core/frame/window.cc
- bridge/core/html/canvas/canvas_rendering_context_2d.cc
- bridge/core/html/canvas/html_canvas_element.cc
The `NativeBindingObject` has the potential possiblity to released between the duration of sync the data from Dart thread and JS thread.
> fix: fix crash when binding object had been released by GC.

- webf/lib/src/launcher/controller.dart
Stop the animation and timer callbacks when Flutter window is hidden or invisible.
https://github.com/openwebf/webf/assets/4409743/a2a523c3-3dc7-4687-ae6a-7d74dc363de2
> feat: pause the activity of webf when app visibility changed.

- bridge/core/dom/events/event_target.cc
- bridge/core/events/event_type_names.json5
- bridge/third_party/quickjs/src/core/runtime.c
- webf/lib/src/dom/comment.dart
- webf/lib/src/dom/container_node.dart
- webf/lib/src/dom/document.dart
- webf/lib/src/dom/element.dart
- webf/lib/src/dom/node.dart
- webf/lib/src/dom/style_node_manager.dart
- webf/lib/src/dom/text_node.dart
- webf/lib/src/dom/window.dart
- webf/lib/src/html/head.dart
- webf/lib/src/launcher/controller.dart
The `styleDirtyElements` member still holding the reference when element disposed.
> fix: fix dart element memory leaks when js gc collected.

- bridge/core/html/html_image_element.cc
- bridge/core/html/html_image_element.h
- bridge/foundation/profiler.h
Fix img Elements didn't get GC collected.
> fix: fix memory leak caused by img element.

- webf/lib/src/bridge/ui_command.dart
- webf/lib/src/dom/element.dart
- webf/lib/src/launcher/controller.dart
Schedule and merge to avoid duplicated calculation of styles.
> feat: optimize performance for recalculate styles.

- bridge/scripts/code_generator/templates/idl_templates/union.cc.tpl
- integration_tests/specs/css/css-images/object-fit.ts
- integration_tests/specs/css/css-transitions/transform-matrix.ts
- webf/lib/src/css/positioned.dart
Fix AtomicString free crash due to built-in-string already freed
> fix: fix atomic string free crash at dispose dart context.

- webf/lib/src/css/text.dart
> fix: iOS FontFamilyFallback on -apple-system style, display error on Vietnamese lang

- bridge/polyfill/src/abort-signal.ts
- bridge/polyfill/src/fetch.ts
- bridge/polyfill/src/index.ts
- integration_tests/scripts/mock_http_server.js
- integration_tests/specs/fetch/fetch.ts
- webf/lib/src/module/fetch.dart
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
> feat: add support for AbortController.

- bridge/core/dart_isolate_context.cc
- bridge/core/dart_isolate_context.h
- bridge/include/webf_bridge.h
- bridge/webf_bridge.cc
- webf/lib/src/bridge/bridge.dart
- webf/lib/src/bridge/to_native.dart
- webf/lib/src/launcher/controller.dart
Prior to WebF 0.16.0 "[Add Dedicated Threading support.](https://github.com/openwebf/webf/pull/512)", the JSRuntime lifecycle was managed by the DartIsolateContext lifecycle.
But in Dedicated threads, the JSRuntime life cycle must be managed by the WebFPage life cycle, and the `runtime_` redundancy created in DartIsolateContext.
Therefore, JSRuntime lifetime managed by WebFPage lifetime in UI thread mode is more uniform
> JSRuntime lifetime managed by WebFPage lifetime

- integration_tests/specs/css/css-flexbox/align-items.ts
- integration_tests/specs/css/css-position/absolute-replaced.ts
- integration_tests/specs/css/css-position/position-static.ts
- webf/lib/src/css/background.dart
- webf/lib/src/css/render_style.dart
- webf/lib/src/html/img.dart
- webf/lib/src/painting/box_fit_image.dart
- webf/lib/src/rendering/box_model.dart
By default, Flutter caches the ImageProvider globally. However, these providers also hold strong references to WebF's elements. 
This PR removes these strong references to ensure elements can be garbage collected freely, except for the ImageProviders.
> fix: fix other element's memory leaks due to ImageProvider cached.

- integration_tests/specs/dom/events/mouseEvent.ts
- webf/lib/src/gesture/gesture_dispatcher.dart
In Flutter, if you use GestureDetector to bind both onTap and onDoubleTap events simultaneously, the following situations will occur:
1. When single-clicking, the onTap event will always be triggered with a 300ms delay;
2. When double-clicking, only the onDoubleTap event will be triggered.
webf uses TapGestureRecognizer's onTap and DoubleTapGestureRecognizer's onDoubleTap to handle click and dblclick events, respectively, which leads to the same issues mentioned above.
We expect behavior that aligns with web standards:
1. The bound click event is triggered immediately when a single click occurs.
2. A double-click event within 300ms triggers two click events and one dblclick event.
Therefore, in this case, we use TapGestureRecognizer's onTap to handle both click and dblclick events …
> refactor(gesture): use tap to simulate double tap

- .gitmodules
```
git submodule update --remote
```
Error: `fatal: Unable to find refs/remotes/origin/v1.7.9 revision in submodule path 'bridge/third_party/quickjs/vendor/mimalloc'`, It is possible that the branch is deleted, No problem with tag
> fix: submodule mimalloc use git tag

- .github/workflows/integration_test_flutter.yml
- bridge/foundation/shared_ui_command.cc
- bridge/foundation/ui_command_buffer.cc
Fix an crash reported by one of our primary customers.
```
Build fingerprint: 'HUAWEI/ALN-AL00/HWALN:12/HUAWEIALN-AL00/104.0.0.165C00:user/release-keys'
#00 0x00000000000db92c /data/app/~~Dn3YtAsInOgqKCZP4g==/Q==/lib/arm64/libwebf.so (BuildId: 0c7f3e4f445ad0da05101c741e1fa30e1e686bec)
webf::UICommandBuffer::clear()
webf/bridge/foundation/ui_command_buffer.cc:128:46
#01 0x00000000000d5b54 /data/app/~~tAYRj4sInOgqKCZP4g==/4SM56a8_ZSWPTzKpQ==/lib/arm64/libwebf.so (BuildId: 0c7f3e4f445ad0da05101c741e1fa30e1e686bec)
webf::SharedUICommand::clear()
webf/bridge/foundation/shared_ui_command.cc:57:18
#02 0x00000000000ebdd4 /data/app/~~DAYRj4sInOgqKCZP4g==/K3c4SM56a8_ZSWPTzKpQ==/lib/arm64/libwebf.so (clearUICommandItems+16) (BuildId: 0c7f3e4f445ad0da05101c741e1fa30e1e686bec)
clearUICommandItems …
```
> fix: fix crash when clear ui commands without commands.

- bridge/core/api/executing_context.cc
- bridge/core/executing_context.cc
- bridge/core/executing_context.h
- bridge/core/native/native_loader.cc
- bridge/include/plugin_api/executing_context.h
- bridge/rusty_webf_sys/src/event_target.rs
- bridge/rusty_webf_sys/src/executing_context.rs
- bridge/rusty_webf_sys/src/lib.rs
- webf/example/lib/main.dart
The UICommands created in Rust now work well in dedicated thread mode.
Revert the default thread mode to dedicated in the example project.
> feat: support dedicated thread mode in rust mode

- webf/lib/src/widget/element_to_widget_adapter.dart
https://github.com/user-attachments/assets/d6198bf6-6b3f-4fa5-bcd4-cbd78a1508bb
This PR adds support for keeping alive every DOM element under the <listview> element, which is implemented using Flutter's ListView widget.
Keeping DOM elements alive can significantly reduce the cost of creating render objects for each one by reusing the previous render objects when scrolling
> feat: optimize listview performance.

- bridge/third_party/quickjs/include/quickjs/quickjs.h
- bridge/third_party/quickjs/src/core/function.c
- bridge/third_party/quickjs/src/core/ic.c
- bridge/third_party/quickjs/src/core/ic.h
- bridge/third_party/quickjs/src/core/object.c
- bridge/third_party/quickjs/src/core/types.h
This patch synchronizes the implementation of [quickjs-ng/quickjs#609](https://github.com/quickjs-ng/quickjs/pull/609) with additional support for the prototype IC
> Fix: Rework inline cache handling.

- bridge/core/binding_call_methods.json5
- bridge/core/dom/element.cc
- bridge/core/dom/element.d.ts
- bridge/core/dom/element.h
- integration_tests/spec_group.json
- integration_tests/specs/dom/elements/custom-element.ts
- integration_tests/specs/dom/events/touchEvent.ts
- integration_tests/specs/dom/nodes/element.ts
- integration_tests/specs/dom/nodes/event-target.ts
- webf/lib/src/dom/element.dart
- webf/lib/src/rendering/box_model.dart
- webf/lib/src/rendering/overflow.dart
Fix the `globalToLocal` wrong answer issue caused by the position: fixed layout.
This scenario usually occurs when an AndroidView is embedded in a `position: fixed` layout using WidgetElement and the outer container scrolls, causing the AndroidView to fail to receive events.
> fix: fix globalToLocal coordinate conversion related to position fixed layout.

- bridge/third_party/quickjs/src/core/builtins/js-function.c
refer: [quickjs-ng](https://github.com/quickjs-ng/quickjs/commit/61dae5d4204a33b7642cc06b1d8d7ea77e21fd21)
We encountered a large number of online crashes, all of which were caused by insufficient memory when calling build arguments, resulting in the add_property call failing and returning null.
So I think there should be a judgment here instead of just letting it crash.
Thread
Scudo ERROR: internal map failure (NO MEMORY) requesting 4KB
pid: 0, tid: 6963 >>> com.xxx.dev <<<
backtrace:
#00 pc 0x00000000000c4bfc /data/app/~~xxx/lib/arm64/libquickjs.so
https://github.com/quickjs-ng/quickjs/issues/1 pc 0x0000000000064cd0 /data/app/~~xxx/lib/arm64/libquickjs.so
https://github.com/quickjs-ng/quickjs/issues/2 pc 0x0000000000065694 /data/app/~~xxx/lib/arm64/libquickjs.so
...
xxx arm64-v8a % …
> Fix: fix crash when add property maybe failed on build arguments

- bridge/polyfill/src/console.ts
Add a new Console API for inspecting complex JavaScript objects.
Example: 
```javascript
const json = {
name: 1,
age: '2',
map: new Map(),
set: new Set(),
fn: function() { return 1; },
undefined: undefined,
null: null,
nest: { nest: {aa: { arr: [1,2,3,4,5]}}}
};
json.map['name'] = new Map();
json.set.add(1);
json.set.add(2);
json.map['name']['age'] = [1,2,3,4,5];
console.inspect(json, 2, 3,4);
```
Result:
```
{
name: 1, 
age: '2', 
map: Map {
name: Map {
age: [1, 2, 3, 4, 5]
}
}, 
set: Set {1, 2}, 
fn: Function {
length: 0, 
name: 'fn', 
prototype: {
constructor: #
}
}, 
undefined: undefined, 
null: null, 
nest: {
nest: {
aa: {
arr: [1, 2, 3, 4, 5]
}
}
}
} 2 3 4
```
> feat: add console.inspect() API for inspecting JavaScript Objects.

- bridge/core/binding_object.cc
- bridge/core/binding_object.h
- bridge/include/webf_bridge.h
- bridge/webf_bridge.cc
- webf/lib/src/bridge/binding.dart
- webf/lib/src/bridge/native_types.dart
- webf/lib/src/gesture/gesture_dispatcher.dart
Fix potential race condition issues when checking the disposed property from the Dart side in multi-threaded mode.
> feat: using std::atomic value types for disposed checks of NativeBindingObject.

- bridge/third_party/quickjs/src/core/runtime.c
https://stackoverflow.com/questions/79195142/recent-msvc-versions-dont-treat-nan-as-constant-workaround
Fixing the compile issue with newer MSVC
> fix: fix windows compile.
